# Generated by Django 5.0.6 on 2025-02-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
        ("inventory", "0015_remove_profile_user_remove_customuser_stores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.shop",
            ),
        ),
    ]
