# Generated by Django 5.0.6 on 2025-01-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.store",
                verbose_name="ร้านค้า",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_code",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="รหัสสินค้า"
            ),
        ),
    ]
