# Generated by Django 5.0.6 on 2025-01-31 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shop",
            options={},
        ),
        migrations.AddField(
            model_name="shop",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shop",
            name="location",
            field=models.CharField(
                blank=True, default="ที่อยู่ยังไม่ได้กำหนด", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="shop",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
