# Generated by Django 5.0.6 on 2025-02-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_shop_admin",
            field=models.BooleanField(default=False, verbose_name="แอดมินร้านค้า"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="แอดมินระบบ"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("superadmin", "ซุปเปอร์แอดมิน"),
                    ("admin", "แอดมินระบบ"),
                    ("shop_owner", "เจ้าของร้าน"),
                    ("shop_admin", "แอดมินร้านค้า"),
                    ("customer", "ลูกค้า"),
                ],
                default="customer",
                max_length=20,
                verbose_name="ประเภทผู้ใช้",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("kg", "กิโลกรัม"),
                    ("g", "กรัม"),
                    ("pcs", "ชิ้น"),
                    ("box", "กล่อง"),
                    ("pack", "แพ็ค"),
                    ("bottle", "ขวด"),
                    ("bag", "ถุง"),
                    ("roll", "ม้วน"),
                    ("sheet", "แผ่น"),
                    ("meter", "เมตร"),
                    ("liter", "ลิตร"),
                    ("Crate", "ลัง"),
                    ("sachet", "ซอง"),
                ],
                default="pcs",
                max_length=10,
                verbose_name="หน่วยสินค้า",
            ),
        ),
    ]
