# Generated by Django 5.0.6 on 2024-10-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("product", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("sales_channel", models.CharField(max_length=255)),
                ("target", models.DecimalField(decimal_places=2, max_digits=10)),
                ("score", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
            ],
        ),
    ]
