# Generated by Django 5.0.6 on 2025-01-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_alter_shop_options_shop_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stores",
            field=models.ManyToManyField(
                blank=True, related_name="owners", to="inventory.store"
            ),
        ),
    ]
