# Generated by Django 5.0.6 on 2024-10-17 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "verbose_name": "คำสั่งซื้อ",
                "verbose_name_plural": "คำสั่งซื้อทั้งหมด",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="category",
        ),
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="order",
            name="score",
        ),
        migrations.RemoveField(
            model_name="order",
            name="target",
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.CharField(
                default="Unknown", max_length=100, verbose_name="ลูกค้า"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="destination",
            field=models.CharField(
                default="ที่อยู่ปลายทาง", max_length=100, verbose_name="ปลายทาง"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.PositiveIntegerField(default=1, verbose_name="จำนวนสินค้า"),
        ),
        migrations.AddField(
            model_name="order",
            name="order_date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="วันที่"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="รหัสคำสั่ง"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="sales_channel",
            field=models.CharField(
                choices=[("store", "หน้าร้าน"), ("online", "ออนไลน์")],
                max_length=100,
                verbose_name="ช่องทางการขาย",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอจัดส่ง"),
                    ("shipped", "จัดส่งแล้ว"),
                    ("cancelled", "ยกเลิก"),
                ],
                max_length=50,
                verbose_name="สถานะ",
            ),
        ),
    ]
