# Generated by Django 5.0.6 on 2025-02-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_customuser_stores"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="location",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ที่ตั้งร้าน"
            ),
        ),
    ]
