# Generated by Django 5.0.6 on 2025-02-01 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_store_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="admin_shops", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
