# Generated by Django 5.0.6 on 2024-12-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_alter_order_customer_alter_order_destination_member"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "สินค้า", "verbose_name_plural": "สินค้าทั้งหมด"},
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="รายละเอียดสินค้า"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_code",
            field=models.CharField(
                default="DEFAULT_CODE",
                max_length=100,
                unique=True,
                verbose_name="รหัสสินค้า",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="product_name",
            field=models.CharField(
                default="Default Product Name",
                max_length=255,
                verbose_name="ชื่อสินค้า",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0, verbose_name="จำนวนในสต็อก"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="ราคา"
            ),
        ),
    ]
