# Generated by Django 5.0.6 on 2024-12-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_product_options_remove_product_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products/", verbose_name="รูปสินค้า"
            ),
        ),
    ]
