# Generated by Django 5.0.6 on 2025-02-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_shop_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_superadmin",
            field=models.BooleanField(default=False, verbose_name="ซุปเปอร์แอดมิน"),
        ),
    ]
