# Generated by Django 5.0.6 on 2025-02-02 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_customuser_is_superadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="added_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="วันที่เพิ่มสินค้า"
            ),
        ),
    ]
