# Generated by Django 5.0.6 on 2024-12-30 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.TextField(default="", verbose_name="รายการ"),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(verbose_name="วันที่"),
        ),
        migrations.AlterField(
            model_name="order",
            name="sales_channel",
            field=models.CharField(max_length=100, verbose_name="ช่องทางการขาย"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(max_length=50, verbose_name="สถานะ"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="img/", verbose_name="รูปสินค้า"
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        related_name="profile",
                    ),
                ),
            ],
        ),
    ]
