# Generated by Django 5.0.6 on 2025-02-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_product_added_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="orders", to="inventory.product"
            ),
        ),
    ]
