# Generated by Django 5.0.6 on 2025-01-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_profile_profile_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="destination",
        ),
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.RemoveField(
            model_name="order",
            name="sales_channel",
        ),
        migrations.RemoveField(
            model_name="order",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="product_images/",
                verbose_name="รูปสินค้า",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="is_cancelled",
            field=models.BooleanField(default=False, verbose_name="ยกเลิกคำสั่งซื้อ"),
        ),
        migrations.AddField(
            model_name="order",
            name="name",
            field=models.CharField(
                default="ไม่ระบุชื่อสินค้า", max_length=255, verbose_name="ชื่อสินค้า"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="ราคา"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product_code",
            field=models.CharField(
                default="ไม่ระบุรหัสสินค้า", max_length=100, verbose_name="รหัสสินค้า"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="จำนวน"),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="รวม (บาท)",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="วันที่"),
        ),
    ]
