# Generated by Django 5.0.6 on 2025-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0009_order_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="รหัสสินค้า"
            ),
        ),
    ]
