# Generated by Django 5.0.6 on 2025-01-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_order_options_remove_order_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="จำนวน"),
        ),
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(verbose_name="จำนวน"),
        ),
    ]
