# Generated by Django 5.0.6 on 2025-02-12 15:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_order_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
    ]
