# Generated by Django 5.0.6 on 2025-02-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0018_order_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[("kg", "กิโลกรัม"), ("pcs", "ชิ้น")],
                default="pcs",
                max_length=10,
                verbose_name="หน่วยสินค้า",
            ),
        ),
    ]
