# Generated by Django 5.0.6 on 2025-02-20 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0019_product_unit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="store",
        ),
        migrations.RemoveField(
            model_name="product",
            name="store",
        ),
        migrations.RemoveField(
            model_name="order",
            name="store",
        ),
        migrations.AlterModelOptions(
            name="shop",
            options={
                "verbose_name": "ร้านค้า",
                "verbose_name_plural": "ร้านค้าทั้งหมด",
            },
        ),
        migrations.RenameField(
            model_name="shopownerrequest",
            old_name="store_name",
            new_name="shop_name",
        ),
        migrations.AddField(
            model_name="stock",
            name="shop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.shop",
                verbose_name="ร้านค้า",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="inventory.shop",
                verbose_name="ร้านค้า",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                related_name="admin_shops",
                to=settings.AUTH_USER_MODEL,
                verbose_name="แอดมินร้านค้า",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="วันที่สร้างร้าน"
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="location",
            field=models.CharField(
                blank=True,
                default="ที่อยู่ยังไม่ได้กำหนด",
                max_length=255,
                verbose_name="ที่ตั้งร้าน",
            ),
        ),
        migrations.AlterField(
            model_name="shop",
            name="name",
            field=models.CharField(max_length=255, verbose_name="ชื่อร้าน"),
        ),
        migrations.AlterField(
            model_name="shop",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="owned_shops",
                to=settings.AUTH_USER_MODEL,
                verbose_name="เจ้าของร้าน",
            ),
        ),
        migrations.DeleteModel(
            name="Store",
        ),
    ]
